### ISSUE TITLE
Kész az első házifeladat

### ISSUE THREAD

**Issue by gregkiss98** [Teaching-projects/SOE-SZTA-2021-KEKW#1]
Légyszíves keress benne hibákat :DD

**Comment by hegyhati** [comment]
- `isAlive` szerintem egy sorban is elintezheto :-)
 - a `setHealth` fv-re igazabol nem sok szukseg van most, csak belso fuggvenybol hasznalod, es csak egy sima ertekadas, amit akar a hivas helyen is megtehetnel, atlathatobb. Akkor van ertelme kitenni kulon fuggvenybe, ha plusz logika tarsul melle (pl monjduk ha 0 ala menne, felhuzza 0-ra). 
 - Zombik tudnak tamadni

**Comment by gregkiss98** [comment]
@hegyhati Felkerültek a javítások.

**Comment by hegyhati** [comment]
Az `isAlive`-nak felesleges a focus. Ha igy lenne, akkor static kellene hogy legyen a fuggveny, mert nem a Jozsi kerdezne meg a Sanyit, hogy eletben van, hanem a Unit osztalytol kerdezzuk meg, hogy a Sanyi eletben van. (Ne kelljen egy peldany ahhoz, hogy lekerdezzuk). De csunya, inkabb mindenki magarol mondja meg, hogy eletben van-e.

attack: -= operator hasznos, atlathatobba teszi a kodot.

getAtk-ban az indentalas szetesett, `if(a==true)` megintcsak bloat, ugyanaz, mint `if(a)`

**Comment by FatBusido** [comment]
@hegyhati Javítottuk a hibákat.

**Comment by hegyhati** [comment]
Jo lesz, a `getAtk` torzset egysorosra oldjatok meg egy ?:-tal :-) Atlathatobb lesz. utana akkor prtotectelem a mastert.

**Comment by FatBusido** [comment]
@hegyhati  Akkor most már elvileg tényleg kész van :D

**Comment by hegyhati** [comment]
wunderbar, mehet a masodik feladat.
